version: '3.8'

services:
  comfy-ui:
    image: comfy_ui:latest
    environment:
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - share=True
      - PIP_BREAK_SYSTEM_PACKAGES=1
    devices:
      - /dev/dxg
    volumes:
      - type: bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
      - ./output:/ComfyUI/output/:rw
      - ./models:/ComfyUI/models/:rw
      - ./custom_nodes:/ComfyUI/custom_nodes/:rw
      - ./InstallCustomNodes.py:/ComfyUI/InstallCustomNodes.py
      # Mount the script into the container
    ports:
      - "8188:8188"
    #command: 
    entrypoint: ["python3", "/ComfyUI/InstallCustomNodes.py"]
    #entrypoint: ["python3", "/ComfyUI/main.py", "--listen"]
    #command: rocminfo
    #entrypoint: /bin/sh  # Use /bin/bash if you prefer Bash
    #command: -c "exec /bin/sh"  # Optional: Run a specific command, if needed
    tty: true
    #stdin_open: true # docker run -i