version: '3.8'

services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern
    container_name: sillytavern
    ports:
      - "8000:8000"
    volumes:
      - ./plugins:/home/node/app/plugins
      - ./config:/home/node/app/config
      - ./data:/home/node/app/data
    networks:
      - my_network

  tabby_api_rocm:
    image: tabby_api_rocm:latest
    environment: 
      - NAME=TabbyAPI
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - share=True
      - PIP_BREAK_SYSTEM_PACKAGES=1
    devices:
      - /dev/dxg
    volumes:
      - type: bind
        source: /usr/lib/wsl
        target: /usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3
      - type: bind
        source: C:\Program Files\WSL\lib
        target: /usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3
      - ./models:/tabbyAPI/models 
      - ./dataAPI/config.yml:/tabbyAPI/config.yml
      - ./dataAPI/config.yml:/tabbyAPI/config_sample.yml 
      - ./dataAPI/cache:/root/.cache
      - ./dataAPI/config.yml:/config.yml
    
    ports:
      - "5000:5000"
    #command: 
    working_dir: /tabbyAPI
    entrypoint: ["python3", "main.py"]
    #entrypoint: ["python3", "/ComfyUI/main.py", "--listen"]
    #command: rocminfo
    #entrypoint: /bin/sh  # Use /bin/bash if you prefer Bash
    #command: -c "exec /bin/sh"  # Optional: Run a specific command, if needed
    tty: true
    #stdin_open: true # docker run -i
    networks:
      - my_network
 
   
networks:
  my_network:
    driver: bridge
