version: '3.8'

services:
  tabby_api_rocm:
    image: tabby_api_rocm:latest
    environment: 
      - NAME=TabbyAPI
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - share=True
      - PIP_BREAK_SYSTEM_PACKAGES=1
    devices:
      - /dev/dxg
    volumes:
      - type: bind
        source: /usr/lib/wsl
        target: /usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3
      - type: bind
        source: C:\Program Files\WSL\lib
        target: /usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3
      - ./models:/tabbyAPI/models 
      - ./data/config.yml:/tabbyAPI/config.yml
    ports:
      - "5000:5000"
    #command: 
    
    entrypoint: ["python3", "tabbyAPI/main.py"]
    #entrypoint: ["python3", "/ComfyUI/main.py", "--listen"]
    #command: rocminfo
    #entrypoint: /bin/sh  # Use /bin/bash if you prefer Bash
    #command: -c "exec /bin/sh"  # Optional: Run a specific command, if needed
    tty: true
    #stdin_open: true # docker run -i